a = input("Type something: ")
print(f"the primitive type of {a} is: ", type(a))
print("Does it only have spaces?", a.isspace())
print("Is it a number?", a.isnumeric())
print("Is it alphabetic?", a.isalpha())
print("Is it alphanumeric?", a.isalnum())
print("Is it uppercase?", a.isupper())
print("Is it lowercase?", a.islower())
print("Is it capitalized?", a.istitle())
